[window]
padding = { x = 4, y = 4 }
decorations = "None"
opacity = 1

[font]
normal = { family = "CaskaydiaCove NerdFont", style = "Regular" }

bold = { family = "CaskaydiaCove NerdFont", style = "Bold" }

italic = { family = "CaskaydiaCove NerdFont", style = "Bold" }

size = 8

[colors]
[colors.primary]
foreground = "#ebdbb2"
background = "#282828"

[colors.normal]
black = "#282828"
red = "#cc241d"
green = "#98971a"
yellow = "#d79921"
blue = "#458588"
magenta = "#b16286"
cyan = "#689d6a"
white = "#a89984"

[colors.bright]
black = "#928374"
red = "#fb4934"
green = "#b8bb26"
yellow = "#fabd2f"
blue = "#83a598"
magenta = "#d3869b"
cyan = "#8ec07c"
white = "#ebdbb2"

[cursor]
style = { shape = "Underline" }

[mouse]
hide_when_typing = true
